Try to get the tests to pass on PyPy, give up
There's only one failure, and it looks like this:

======================================================================
FAIL: /home/mg/src/new-zope-order/zope.sqlalchemy/src/zope/sqlalchemy/README.txt
Doctest: README.txt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pypy/lib-python/2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for README.txt
  File "/home/mg/src/new-zope-order/zope.sqlalchemy/src/zope/sqlalchemy/README.txt", line 0

----------------------------------------------------------------------
File "/home/mg/src/new-zope-order/zope.sqlalchemy/src/zope/sqlalchemy/README.txt", line 177, in README.txt
Failed example:
    str(session.query(User).all()[0].name)
Expected:
    'bob'
Got:
    'ben'
----------------------------------------------------------------------
File "/home/mg/src/new-zope-order/zope.sqlalchemy/src/zope/sqlalchemy/README.txt", line 189, in README.txt
Failed example:
    bob.name
Expected:
    Traceback (most recent call last):
    DetachedInstanceError: Instance <User at ...> is not bound to a Session; attribute refresh operation cannot proceed
Got:
    'ben'

----------------------------------------------------------------------

So we're getting stale data from a new session object through which we've just
modified an object.